steps:
  - name: debian
    script: |
      #!/bin/sh
      cpan install File::HomeDir
      apt-get update
      apt-get install libstring-shellquote-perl
      apt-get install -y libwww-perl
      apt-get install python3-pycurl
      apt-get install -y python3-requests
      apt-get install -y python3-debian
      apt-get install -y equivs
      apt-get install -y apt-utils
      apt-get install -y mmdebstrap
      ./debrebuild.pl --buildresults=./artifacts --builder=mmdebstrap gzip_1.10-2_all-amd64-source.buildinfo 


