steps:
  - name: "docker.io/library/perl"
    script: |
      #!/bin/sh
      #echo hello
      #cpan install File::HomeDir
      #apt-get update
      #apt-get install -y libstring-shellquote-perl
      #apt-get install -y libwww-perl
      #apt-get install -y python3-pycurl
      #apt-get install -y python3-requests
      #apt-get install -y python3-debian
      #apt-get install -y equivs
      #apt-get install -y apt-utils
      #apt-get install -y mmdebstrap
      #vim simple.txt
      pwd
      ls
      echo hello > simple.txt
      mkdir simple
      mkdir simple/simple2
      #./debrebuild.pl --buildresults=./artifacts --builder=mmdebstrap gzip_1.10-2_all-amd64-source.buildinfo
artifacts:
  objects:
    location: 'gs://jeffinbiju/cloud-aoss-1p-dev' 
    paths: ['simple']  


