# wf-debian.yaml
name: newwf1
serviceAccount: "projects/cloud-aoss-1p-dev/serviceAccounts/cloudbuildgen2@cloud-aoss-1p-dev.iam.gserviceaccount.com"


params:
  - name: pkg
    default: apt_2.2.4_amd64
workspaces:
  - name: default-workspace
    volume:
      storage: 10gb
pipeline:
  spec:
    workspaces:
      - name: default-workspace
  tasks:
      - name: build-pkg
        #runAfter:
        #- "clone-repo"
        workspaces:
          - name: source
            workspace: default-workspace
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: pull-and-build
              image: docker.io/library/perl
              script: |
                #!/bin/sh
                echo $(params.pkg)
                #cpan install File::HomeDir
                #apt-get update
                #apt-get install -y libstring-shellquote-perl
                #apt-get install -y libwww-perl
                #apt-get install -y python3-pycurl
                #apt-get install -y python3-requests
                #apt-get install -y python3-debian
                #apt-get install -y equivs
                #apt-get install -y apt-utils
                #apt-get install -y mmdebstrap
                #cd $(workspaces.source.path)
                #ls
                #./debrebuild.pl --buildresults=./artifacts --builder=mmdebstrap ./buildinfos/$(params.pkg).buildinfo
                #echo "sha256:" | tee hash
                #sha256sum artifacts/$(params.pkg).deb | cut -d " " -f 1 >> hash 
                #tr -d '\n' < hash > $(results.pkg_ARTIFACT_DIGEST.path)
                #ls artifacts | tr -d '\n' | tee $(results.pkg_ARTIFACT_URI.path) 
      - name: store
        #runAfter: 
        #- "clone-repo"
        workspaces:
          - name: source
            workspace: default-workspace
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: store-artifact    
              image: gcr.io/cloud-builders/gcloud
              script: |
                cd $(workspaces.source.path)
                gcloud artifacts apt upload apt-repo --location=us-central1 --source=artifacts/$(params.pkg).deb


options:
  executionEnvironment:
    workerPool: "projects/cloud-aoss-1p-dev/locations/us-central1/workerPools/jeffin-test-pool"


